on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Pending Commit Status
        uses: ouzi-dev/commit-status-updater@v1.0.4
        with:
          status: pending

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Yarn
        run: yarn && yarn add -P graphql

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Success Commit Status
        if: success()
        uses: ouzi-dev/commit-status-updater@v1.0.4
        with:
          status: success
          url: https://www.npmjs.com/package/graphql-query-vars-cleaner
          description: "published to NPM"

      - name: Failure Commit Status
        if: failure()
        uses: ouzi-dev/commit-status-updater@v1.0.4
        with:
          status: failure
          description: "publish failed"
          
