on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Pending Commit Status
        run: >
          curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA -H "Authorization: token ${{ github.token }}" -d '{"state":"pending","target_url":"https://www.npmjs.com/package/graphql-query-vars-cleaner","description":"publishing to NPM","context":"publish"}'

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Yarn
        run: yarn && yarn add -P graphql

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Success Commit Status
        if: success()
        run: >
          curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA -H "Authorization: token ${{ github.token }}" -d '{"state":"success","target_url":"https://www.npmjs.com/package/graphql-query-vars-cleaner","description":"published to NPM","context":"publish"}'

      - name: Failure Commit Status
        if: failure()
        run: >
          curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA -H "Authorization: token ${{ github.token }}" -d '{"state":"failure","target_url":"https://www.npmjs.com/package/graphql-query-vars-cleaner","description":"publish failed","context":"publish"}'
          