on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Pending Commit Status
        run: >
          curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA -H "Authorization: token ${{ github.token }}" -d '{"state":"pending","description":"testing new commit","context":"test"}'

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Yarn
        run: yarn && yarn add -P graphql

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Success Commit Status
        if: success()
        run: >
          curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA -H "Authorization: token ${{ github.token }}" -d '{"state":"success","description":"tests passed","context":"test"}'

      - name: Failure Commit Status
        if: failure()
        run: >
          curl -X POST https://api.github.com/repos/$GITHUB_REPOSITORY/statuses/$GITHUB_SHA -H "Authorization: token ${{ github.token }}" -d '{"state":"failure","description":"tests failed","context":"test"}'
          