on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        id: deployment
        with:
          token: "${{ github.token }}"
          target_url: https://www.npmjs.com/package/graphql-query-vars-cleaner

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Yarn
        run: yarn && yarn add -P graphql

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://www.npmjs.com/package/graphql-query-vars-cleaner
          state: "success"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://www.npmjs.com/package/graphql-query-vars-cleaner
          state: "failure"
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
