on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set In Progress Status
        uses: unacast/actions-github-deployment-status
        with:
          github_token: ${{ secrets.TOKEN }}
          status: in_progress
          description: "publish in progress..."
      - name: Checkout
        uses: actions/checkout@v1
      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: Yarn
        run: yarn && yarn add -P graphql
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Set Success Status
        uses: unacast/actions-github-deployment-status@v0.2
        with:
          github_token: ${{ secrets.TOKEN }}
          status: success
          description: "published"
      - name: Set Failure Status
        if: failure()
        uses: unacast/actions-github-deployment-status@v0.2
        with:
          github_token: ${{ secrets.TOKEN }}
          status: failure
          description: "publish failed"
